#name: ci
#
#on:
#  push:
#    tags:
#      - 'v*.*.*'
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v2
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Set release version output
#        id: vars
#        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
#      -
#        name: Check release version output
#        env:
#          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
#        run: |
#          echo $RELEASE_VERSION
#          echo ${{ steps.vars.outputs.tag }}
#      -
#        name: Build and push
#        env:
#          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          platforms: linux/amd64
#          tags: davikingcode/nginx-php-fpm:${{ env.RELEASE_VERSION }}
